---
title: "Evaluation and Simulation of the Exponential Distribution"
output:
  html_document:
    keep_md: true
---

```{r setoptions,echo = FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, restult = "hide")
```

##by Michael Gregory

###Overview: In this project I will investigate the exponential distribution in R and compare it with the Central Limit Theorem.  I will compare the population and sample mean as well as the population and sample variance.

###Simulations: The exponential distribution will be simulated in R with rexp(n, lambda) where lambda is the rate parameter. 

-Using a lambda of .2, generate 1000 simulations of 40 random exponential values and also calculate the means of those 1000 simulations.


 I will use a lambda = 0.2 for all 1000 simulations.  I will investigate the distribution of averages of 40 exponentials. Note that you will need to do a thousand simulations.  

###Sample Mean versus Theoretical Mean: 
-The mean of exponential distribution is 1/lambda and the standard deviation is also 1/lambda.

Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.


###Sample Variance versus Theoretical Variance: Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances.


###Distribution: Via figures and text, explain how one can tell the distribution is approximately normal.

???Central Limit Theorem.  ???


